// This file is auto-generated by Lovable. Local-dev OAuth bypass added below.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import type { OAuthProvider } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
import { isLocalDevHost, signInWithOAuthLocal } from "./local-oauth";

const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: OAuthProvider, opts?: SignInOptions) => {
      // localhost is rejected by Lovable; local-oauth uses 127.0.0.1 + /~oauth proxy.
      const result = isLocalDevHost()
        ? await signInWithOAuthLocal(provider)
        : await lovableAuth.signInWithOAuth(provider, {
            ...opts,
            extraParams: {
              ...opts?.extraParams,
            },
          });

      if ("redirected" in result && result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens!);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
