/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as MockNewRouteImport } from './routes/mock-new'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CompareMockIdRouteImport } from './routes/compare.$mockId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const MockNewRoute = MockNewRouteImport.update({
  id: '/mock-new',
  path: '/mock-new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareMockIdRoute = CompareMockIdRouteImport.update({
  id: '/compare/$mockId',
  path: '/compare/$mockId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/mock-new': typeof MockNewRoute
  '/settings': typeof SettingsRoute
  '/compare/$mockId': typeof CompareMockIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/mock-new': typeof MockNewRoute
  '/settings': typeof SettingsRoute
  '/compare/$mockId': typeof CompareMockIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/mock-new': typeof MockNewRoute
  '/settings': typeof SettingsRoute
  '/compare/$mockId': typeof CompareMockIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/library' | '/mock-new' | '/settings' | '/compare/$mockId'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/auth' | '/library' | '/mock-new' | '/settings' | '/compare/$mockId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/library'
    | '/mock-new'
    | '/settings'
    | '/compare/$mockId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LibraryRoute: typeof LibraryRoute
  MockNewRoute: typeof MockNewRoute
  SettingsRoute: typeof SettingsRoute
  CompareMockIdRoute: typeof CompareMockIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-new': {
      id: '/mock-new'
      path: '/mock-new'
      fullPath: '/mock-new'
      preLoaderRoute: typeof MockNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$mockId': {
      id: '/compare/$mockId'
      path: '/compare/$mockId'
      fullPath: '/compare/$mockId'
      preLoaderRoute: typeof CompareMockIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LibraryRoute: LibraryRoute,
  MockNewRoute: MockNewRoute,
  SettingsRoute: SettingsRoute,
  CompareMockIdRoute: CompareMockIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
